#!/usr/bin/env bash
# Install Nginx and change the html file
sudo apt-get update -y
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo systemctl restart nginx.service
