#!/usr/bin/env bash
# Install and configure a load balancer
sudo apt-get update -y
sudo apt-get install haproxy -y

confi = "\
frontend main
      bind *:80
      mode http
      default_backend nodes

backend nodes
      balance roundrobin
      server 1187-web-01 35.237.103.2:80 check
      server 1187-web-02 18.209.63.81:80 check"

echo "$confi" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
