#!/usr/bin/env bash
#script with options
start()
{
    echo "manage_my_process started"
    sudo touch /var/run/my_process.pid
    sudo chmod 777 /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    ./manage_my_process &
}
stop()
{
    pgrep -f manage_my_process | xargs kill -15 &
    sudo rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}
restart()
{
    pgrep -f manage_my_process | xargs kill -15 &
    sudo rm /var/run/my_process.pid

    sudo touch /var/run/my_process.pid
    sudo chmod 777 /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    ./manage_my_process &
    echo "manage_my_process restarted"
}
case "$1" in
     start) start;;
     stop) stop;;
     restart) restart;;
     *) echo "Usage: manage_my_process {start|stop|restart}";;
esac
