#!/usr/bin/env bash
#script with options
start()
{
    ./manage_my_process &
    sudo touch /var/run/my_process.pid
    sudo chmod 777 /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
}
stop()
{
    kill $(cat /var/run/my_process.pid) &
    sudo rm -rf /var/run/my_process.pid
    echo "manage_my_process stopped"
}
restart()
{
    kill $(cat /var/run/my_process.pid) &
    sudo rm -rf /var/run/my_process.pid

    ./manage_my_process &
    sudo touch /var/run/my_process.pid
    sudo chmod 777 /var/run/my_process.pid
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
}
case "$1" in
     start) start;;
     stop) stop;;
     restart) restart;;
     *) echo "Usage: manage_my_process {start|stop|restart}";;
esac
exit 0
