#!/usr/bin/env bash
#print holbertonshool 10 times and hi in 9
i=0
while [ $i -lt 10 ]; do
    if [ $i -eq 8 ]
    then
      	echo "Hi"
    else
	echo "Holberton School"
    fi
    let "i += 1"
done
