#!/usr/bin/env bash
# Execute for nginx user
pkill -f apache2
sed -i "s/80/8080" /etc/nginx/sites-enabled/defaul
sudo chmod 777 /etc/nginx/nginx.conf
sed -i "1iuser nginx;" /etc/nginx/nginx.conf
sudo -u nginx service nginx start
